export interface Client {
  id: string; // uuid, generated by Supabase
  code: string;
  name: string;
  type: string;
  addr1: string;
  addr2: string;
  town: string;
  county: string;
  postcode: string;
  contact_number: string;
  email: string;
}

export type ClientInsert = Omit<Client, 'id'>;
